export const QUERY_POKEMON_ACTION = 'QUERY_POKEMON_ACTION';
export const PROCESS_POKEMON_ACTION = 'PROCESS_POKEMON_ACTION';
export const SET_FAVOURITE_ACTION = 'SET_FAVOURITE_ACTION';
export const VIEW_DETAILS_ACTION = 'VIEW_DETAILS_ACTION';
export const HIDE_DETAILS_ACTION = 'HIDE_DETAILS_ACTION';
export const POKEMONS_LOADED_ACTION = 'POKEMONS_LOADED_ACTION';